### ISSUE TITLE
WinServer 2019 create fails

### ISSUE THREAD

**Issue by bharpe** [willnx/vlab#26]
I tried to create a WinServer 2019 Instance using the following command which brought about the error shown after it:

```
PS C:\Users\harpew> vlab create winserver -i 2019 -n BHWin2019
Creating a new instance of Microsoft Server 2019
Error: File ds:///vmfs/volumes/5c8c4bc0-83ffed20-a528-e4434b4a2d50/_deviceImage-0.iso was not found
PS C:\Users\harpew>
```

**Comment by willnx** [comment]
@bharpe Sorry for the slow response; been on vacation/holiday/PTO/etc.

I can't look into that error more until tomorrow (when I'm back in the office).
* In the mean time, have you tried deleting/remaking the VM? If so, do you get a similar error?
* Are you able to list (`vlab status`) the items in your lab?

**Comment by bharpe** [comment]
I did retry making the WinServer 2019 server, I tried using both 2019 and 2019R2 as the image designation. I could not delete the instances of them because none were created.  Yes, I can list (vlab status) the items in my lab, which is working pretty well.  Thank you so much for your work on this project.

**Comment by willnx** [comment]
Doh! I'm an idiot... I forgot to _take the ISO image out_ of the virtual CD drive. 
The error you're seeing is that the OVF is still pointing to that ISO image in the virtual CD drive.

The vCenter UI handles this situation OK (which is the lazy way I tested the OVA), but my automation talking to the vCenter API clearly doesn't. Sorry about that! 

I'll re-roll the image; should have this fixed sometime today.

**Comment by willnx** [comment]
OK! Re-rolled the image and tested; seems to be working:
```
PS C:\Users\willhn> vlab create winserver -n derp -i 2019
Creating a new instance of Microsoft Server 2019
Creating an RDP port mapping rule
Type     :  WinServer
Version  :  2019
State    :  poweredOn
IPs      :  fe80::2c7d:b75a:8bd9:d529 192.168.1.178
Console  :  https://vlab.emc.com/api/1/link/92487d4055b7eebced50916bfa6619d7

Use 'vlab connect winserver --name derp' to access your new Microsoft Server
PS C:\Users\willhn> vlab connect winserver --name derp
Lookin up connection information for derp
```

Sorry for the derp bug!

**Comment by bharpe** [comment]
No problem.  Thank you for doing so much.
