### ISSUE TITLE
ECS does not have enough RAM to initialize

### ISSUE THREAD

**Issue by IsaiahStotler** [willnx/vlab#27]
When deploying ECS 3.2.2.0 per https://ecsce.readthedocs.io/en/latest/installation/OVA_Installation.html, step 4 fails with the following message:
```
TASK [common_baseline_check : Common | Check RAM size] **********************************************************************************************************************************************
fatal: [192.168.1.170]: FAILED! => {"changed": false, "failed": true, "msg": "Total RAM available for ECS is less than 15500MB (1830MB reported by node)"}

PLAY RECAP ******************************************************************************************************************************************************************************************
192.168.1.170              : ok=6    changed=0    unreachable=0    failed=1

Playbook run took 0 days, 0 hours, 0 minutes, 2 seconds
Operation failed.
```

Per the same link the following requirements are needed:

4 CPU Cores
16 GB Memory
16 GB Minimum system block storage device
104 GB Minimum additional block storage device in a raw, unpartitioned state.
CentOS 7 Minimal installation (ISO- and network-based minimal installs are equally supported)

**Comment by willnx** [comment]
Sorry about that! Those images only have 2 GB of RAM. 
I can fix this pretty quickly; ETA is end of the week 😅 

![image](https://user-images.githubusercontent.com/12264343/58137821-a4dbad00-7be8-11e9-97ce-2c5b370034eb.png)

**Comment by willnx** [comment]
Updated the docs for the ECS username/password
https://github.com/willnx/vlab_docs/commit/a9101ba107464b48f18c0ef1282b44fb1ec4dcdc#diff-f3f2750f35a235322be128bf49aae043

**Comment by willnx** [comment]
Fix is live. Let me know if you have additional issues with the VM "hardware" settings
