### ISSUE TITLE
Unable to run vlab init without putty/winscp installed

### ISSUE THREAD

**Issue by Daeden-JL** [willnx/vlab#33]
> In order for 'vlab connect' to work, you'll need to have a
> browser, an SSH client, and an SCP client installed.
> Based on your OS, I can use the following:
> chrome, firefox, putty, mstsc, winscp, SecureCRT
> 
> Note: mstsc is the default RDP client that comes with Windows
> 
> If you do not have the SSH, RDP, and SCP clients as well as a supported browser
> installed you'll be wasting time by continuing with this config setup.
> Continue with config setup? [Yes/no]
> Great! Give me a couple of minutes to find those programs
> 
> Uh oh, there's a problem. I wasn't able to find everything under C:\.
> Here are the programs I was able to locate:
>         chrome mstsc
> Please install the missing software, then re-run the 'vlab init' command.
> Error: Missing required dependencies
> PS C:\windows\system32>

This should prompt the user to confirm that they want to continue instead of exiting.

**Comment by willnx** [comment]
It cannot continue. That's why it exists.

I mean, the CLI says:
```
If you do not have the SSH, RDP, and SCP clients as well as a supported browser
installed you'll be wasting time by continuing with this config setup.
Continue with config setup? [Yes/no]
```
And the documentation calls out those prerequisites (and includes links to download Putty and Winscp):
https://vlab.emc.com/getting_started.html#prerequisites-dependencies

Pretty sure the video links in the Getting Started doc note the requirements too.

What would do you want it to prompt you with? Like, wait for you to install those dependencies, then continue?

**Comment by Daeden-JL** [comment]
It would be nice to have a warning asking to proceed without them. 
I have them installed, but they are not in the standard path, I'm guessing that is why the installer couldn't see them.

Does the installer use those applications or is it preventing a PEBCAK error?

On a random note, ssh seems to be included in PowerShell by default with the latest corp image.

**Comment by willnx** [comment]
The `vlab connect` subcommand requires them, so basically yeah, to prevent a PEBCAK error.
Without those apps, users would have a really hard time connecting to things within their lab.

The vLab CLI walks the `C` drive on Windows ([link to code](https://github.com/willnx/vlab_cli/blob/master/vlab_cli/lib/configurizer.py#L79)), but if you have a `D` drive, or `E` direct, etc, it wouldn't find it.

I'll checkout the built-in SSH feature of the CORP image on Monday; thanks for the tip!

**Comment by willnx** [comment]
Poked around with `ssh` on the CORP image. It's just OpenSSH (like Linux), so it has the same issue as Linux: needs to be ran inside a shell. 

I'm not going to support that as a valid SSH agent for vLab for the following:
* No support for interactive username - OpenSSH doesn't prompt for _"which user to you want to login as"_
* Gnarly aspect of trying to fork a shell with a per-defined command to execute
* Which shell hell - `cmd` vs `PowerShell` and the necessary config to support _more than one_

**Comment by Daeden-JL** [comment]
Ignoring the built-in ssh, could we still look at this for advanced users. 
A warning that tells the user that they won't be able to connect to the cluster without installing the tools, but will allow them to continue?

**Comment by willnx** [comment]
No. Why would anyone want to allow users to deploy _broken software_? It's bad design to let users shoot themselves in the foot like that.
