### ISSUE TITLE
Option to disable slow type

### ISSUE THREAD

**Issue by Daeden-JL** [willnx/vlab#34]
Would it be possible to have a flag that would print the output instantly? 
I like the slow type during first installs and setups. but not during daily usage.

**Comment by willnx** [comment]
The typewrite effect is pretty minimal once you get past the initial install. Like, when you deploy a new component, it'll scroll something like:

```
Deploy a new InsightIQ instance running 4.1.2
```
Followed with that little spinning wheel of death. So that scroll text is maybe 1 second of your day. The deploy is going to take tens of minutes. I'm not trying to be confrontational, but I don't see what's so bad about it.

The only time you get _a pile_ of scroll text is when [clippy](https://github.com/willnx/vlab_cli/tree/master/vlab_cli/lib/clippy) is invoked, and that only happens as the result of bad user input.

What daily of the scroll text do you find annoying?

**Comment by Daeden-JL** [comment]
That's fair, mostly it is the initial install and then when trying to print the list of network connections. It isn't bad, and honestly I like the effect. It would just be nice to have a flag to disable it on occasion.

**Comment by willnx** [comment]
Yeah, and you're not the first one to request this 😅 So fair enough, I'll add a flag to the `vlab` base command. It'll be a fair amount of work, so stay tuned for details.

**Comment by willnx** [comment]
List of _all the things_ that touch the `typewriter` function:
```
vlab_cli/vlab_cli$ grep -r typewriter * | cut -d\: -f1 | sort -u | grep -v Binary
lib/clippy/connect.py
lib/clippy/onefs.py
lib/clippy/portmap.py
lib/clippy/utils.py
lib/clippy/vlab_init.py
lib/widgets.py
subcommands/apply/snapshot.py
subcommands/connect/base.py
subcommands/create/cee.py
subcommands/create/centos.py
subcommands/create/claritynow.py
subcommands/create/ecs.py
subcommands/create/esrs.py
subcommands/create/esxi.py
subcommands/create/icap.py
subcommands/create/iiq.py
subcommands/create/onefs.py
subcommands/create/portmap.py
subcommands/create/router.py
subcommands/create/snapshot.py
subcommands/create/windows.py
subcommands/create/winserver.py
subcommands/delete/portmap.py
subcommands/delete/snapshot.py
subcommands/init.py
subcommands/status.py
```

It's defined within the `widgets.py` module. 

My initial thought was to bind the correct typewriter logic (line by line or word by word) to the Click context, which would work well for all the `subcommands`. The part I need to think on is how to make `clippy` respect a CLI argument 🤔.

**Comment by willnx** [comment]
After trying to do it _the hard way_ for about an hour, I took a break and thought of this much simpler solution:

https://github.com/willnx/vlab_cli/commit/3163e946775f613b54e0b5f552704b7d2b3d4349#diff-a6177fcb4650c730421a5adc4c414b2b

After that change, if users supply the `-o` or `--no-scroll` argument, the whole message is pumped out to the terminal all at once. 

Examples of using the new argument:

- `vlab -o status`
- `vlab -o token --refresh`
- `vlab --no-scroll create onefs`

**Comment by willnx** [comment]
This feature will ship with the `2019.6.17 +1`  version of the CLI, i.e. after whatever I add next.

(note: the version follows the pattern `year`.`month`.`day`)
