### ISSUE TITLE
Vlan Support

### ISSUE THREAD

**Issue by Daeden-JL** [willnx/vlab#37]
Would it be possible to setup vlan support? This would be a huge boon to network troubleshooting!

**Comment by willnx** [comment]
Great question!

I looked into this when setting up the [vLab vlan service](https://github.com/willnx/vlab_vlan), but VMware's switches do not support [IEEE 802.1ad](https://en.wikipedia.org/wiki/IEEE_802.1ad) (i.e. QinQ). 

Without support for QinQ in a [DVswitch](https://www.vmware.com/products/vsphere/distributed-switch.html), there's no way I can provide a routable network with user-level vlans. 

There might be some 3rd party virtual switch that can be used in vSphere, or maybe something with NSX-t that enables QinQ. If you wanted to look into that, I'd really appreciate it!

**Comment by willnx** [comment]
backlogging this request. I mean, it's a great request, but I'm just not sure that it's feasible until VMware adds support.
