### ISSUE TITLE
getting authentication error when rdp to vlab icap

### ISSUE THREAD

**Issue by JohnVo620** [willnx/vlab#4]
C:\Windows\System32>vlab --version
vlab, version 0.2.4

- After creating icap via vlab
- trying to connect to icap via rdp, the following pop-up error will occur (see screenshot)

- To fix:
connect to icap via console
Go to remote settings, and change option to "Allow connections from computers running any version of Remote Desktop (less secure)"
![rdp_icap_error](https://user-images.githubusercontent.com/45999637/50706163-0aa90d00-102b-11e9-8315-e0d7614d60e5.png)

![icap_server_remote_setting](https://user-images.githubusercontent.com/45999637/50706187-1d234680-102b-11e9-9305-d6e323116681.png)

**Comment by willnx** [comment]
Hi John, I've re-rolled the ICAP ova and RDP looks like it's working as expected now. Also, I fixed that issue with adjusting the tread count on the ICAP server. Let me know if you have any issues with the updated image. Thanks again for finding this for me!
