### ISSUE TITLE
Enhancement to backspace or delete on command-line

### ISSUE THREAD

**Issue by woodwardc** [willnx/vlab#42]
Please add a feature to either backspace or delete text.
Currently if you mistype you have to cntrl+c and start over

**Comment by willnx** [comment]
@woodwardc Could you provide a bit more context? I mean, I'm able to delete the input from a prompt already:

![vlab_delete_input](https://user-images.githubusercontent.com/12264343/60280846-99029b00-98b8-11e9-88ab-5c44f32aabcb.gif)

**Comment by willnx** [comment]
Given the lack of response, and that this functionality works for me, I'm going to close this issue.

@woodwardc If you can provide more context, feel free to re-open the issue.
