### ISSUE TITLE
Request: API documentation, etc

### ISSUE THREAD

**Issue by pianomanzero** [willnx/vlab#43]
Re: https://vlab.emc.com/for_developers/base.html 
Can we have a doc for the API (and other relevant documentation)?  I'd like to eventually get around to developing a GUI for vLab if I can find the time.

**Comment by willnx** [comment]
Absolutely! I'll update the docs to include the API end points, what they do, and what headers they might need a client to send.

The trickiest part I've seen when it comes to API docs is providing examples in a useful yet language agnostic way.

I love Python's [requests](https://2.python-requests.org/en/master/) library, but not everyone loves/understands Python. A lot of _other docs_ just provide [curl](https://linux.die.net/man/1/curl) examples (which are rather ugly/ and not everyone knows curl). If you have any thoughts on this part, I've love some input! 😄

**Comment by pianomanzero** [comment]
Awesome! Yeah, I haven't decided what I want to write it in yet, it's been a number of years since i've done any desktop app development, but I'll start fiddling around with it and let ya know.

**Comment by willnx** [comment]
I vote for writing a GUI in JavaScript because:

- It's the _defacto_ language for interactive web sites
- You can leverage [Electron](https://electronjs.org) to reuse the same source code and make a desktop app
- It integrates with [WebAssembly](https://webassembly.org), and so does [Rust](https://www.rust-lang.org), which means a CLI and a GUI can _share the same client library_ (when I get around to writing that :wink:)

**Comment by pianomanzero** [comment]
Cool beans. I've never used Electron and it's been years since i've needed to use JS (was server-side C++/Java dev before Isilon, ha!), but i've got my dev env set up to start putting things together with Electron. I'm fiddling with it now and I'll update the thread once i have something workable.

**Comment by willnx** [comment]
Hey @pianomanzero, I updated the docs and pushed them to the server. Give them a look, and let me know what else it needs.

I'll keep this open for a few days, just so you don't have to reopen/make a new issue if the updated docs aren't useful enough.
