### ISSUE TITLE
Give dependency location on vlab init

### ISSUE THREAD

**Issue by Daeden-JL** [willnx/vlab#48]
Would it be possible to have vlab ask for the path to your programs if it can't find them?

 > In order for 'vlab connect' to work, you'll need to have a
 > browser, an SSH client, and an SCP client installed.
 >Based on your OS, I can use the following:
 >chrome, firefox, putty, mstsc, winscp, SecureCRT

 >Note: mstsc is the default RDP client that comes with Windows

 >If you do not have the SSH, RDP, and SCP clients as well as a supported browser
 >installed you'll be wasting time by continuing with this config setup.
 >Continue with config setup? [Yes/no] yes
 >Great! Give me a couple of minutes to find those programs

 >Uh oh, there's a problem. I wasn't able to find everything under C:\.
 >Here are the programs I was able to locate:
 >        putty chrome mstsc
 >Please install the missing software, then re-run the 'vlab init' command.
 >Error: Missing required dependencies

This would allow programs from custom locations to be used.
Thanks!

**Comment by willnx** [comment]
You already can! 😄 

In your home directory, there's a `.vlab` folder (if not, just make it).
Inside that folder is a `config.ini` file (again, if it's not there, just make it).

The `vlab init` command just automates creating and configuring that config file.
It's a standard INI format; here's a toy example of how it's formatted:
```
[SCP]
agent=winscp
location=C:\\some\\path\\WinSCP.exe

[SSH]
agent=putty
location=C:\\some\\path\\putty.exe

[BROWSER]
agent=firefox
location=C:\\some\\path\\firefox.exe

[RDP]
agent=mstsc
location=C:\\some\\path\\mstsc.exe
```

If that file already exists (and has the expected sections/keys), when you run `vlab init`, the whole section that auto-generates that file will be skipped.

**Comment by Daeden-JL** [comment]
Thanks!
