### ISSUE TITLE
Better OneFS Autoconfig

### ISSUE THREAD

**Issue by willnx** [willnx/vlab#59]
The autoconfig logic for OneFS is... shit 😅. It uses the HTML console via [Selenium](https://selenium.dev) to respond to the OneFS config wizard. However, the vCenter HTML console is an [HTML5 Canvas](https://www.w3schools.com/graphics/canvas_intro.asp), which means you can't use the normal Selenium API for tracking changes to the element. The result is a pile of _dumb sleeps_ by the OneFS autoconfig to guess when the OneFS config wizard has reached the next prompt 😞. To put another way, the current OneFS autoconfig is _literally_ like someone typing with their eyes closed to respond to the prompts of the OneFS config wizard. Slowdowns in the network, VM, etc makes the sleeps:
**A**) much higher than needed 
and 
**B**) prone to be wrong.

I noticed that a [websocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API) was being used to transfer data between the browser and vCenter and thought, _"can Selenium see Websocket traffic?"_ 🤔 Turns out, [yes](http://www.amitrawat.tech/post/capturing-websocket-messages-using-selenium/)!

This means we can make the autoconfig _much_ more reliable by checking for incoming messages from the websocket. Ideally, we'd be able to parse the data to know when we're _at the next prompt_, but at worst we could trigger off a _lack of incoming data_ from the websocket to have a _better guess_ at when we should start responding to an (expected) prompt!

**Comment by BinaryVixen899** [comment]
This explains a lot :P
