### ISSUE TITLE
Portmapping issues with OneFS 7216 cluster 

### ISSUE THREAD

**Issue by mfreemanjr** [willnx/vlab#60]
Creating the cluster is successful, but cannot connect to this cluster via ssh or https. Remote console connection okay. 
Attempted https connection via gateway IP and port 50056. Connection redirects to another working vm with port 50036 
Chrome debug:
Request URL: https://10.241.80.90:50056/session/1/session?_dc=1578496021676
Request Method: GET
Status Code: 401 Unauthorized
Remote Address: 10.241.80.90:50056
Referrer Policy: no-referrer-when-downgrade
Maybe an issue with the OneFS version? Possibly needs additional configuration?

**Comment by willnx** [comment]
Yeah, for some reason the autoconfig isn't applying the ext IPs to the machine.

As a workaround, you can manually do that from the terminal:
```
vlab connect onefs -n <your node> -p terminal
```

**Comment by mfreemanjr** [comment]
Turns out I originally created this lab using an IP from my existing sc zone. Doh! 
So I deleted and created a new lab. However, issues still exist. 
 vlab create onefs -i 7.2.1.6 -n v7216 -c 3 -x 192.168.1.70 192.168.1.75

Though I've given a range for the external interfaces, I've logged into the cluster via console and see there are no subnets/pool/external interfaces configured. Perhaps this needs to be done manually on this version of OneFS?

**Comment by mfreemanjr** [comment]
Manually configured a nodes subnet, pool, and ext interface while logged into the console and was able to log in via webui. then got the other other interfaces added. seems to be working now. 

This can issue can be closed...unless its needed to fix the autoconfig?

**Comment by willnx** [comment]
@mfreemanjr Thanks! Yeah, let's keep it open until I can fix (or at least determine the issue with) the autoconfig for 7.2.16.

**Comment by willnx** [comment]
Blake Dunmire noticed that OneFS 7.2.1.6 needs _one less `enter`_ key press after configuring the internal network.
