### ISSUE TITLE
DataIQ v2 change hard disk requitement

### ISSUE THREAD

**Issue by kawaiy2** [willnx/vlab#77]
DataIQ v2 hard disk requirement is changed from 40GB to 80GB.
Then I tried to install v2 is fail.
==[ Please fix below errors and re-run precheck... ]==
=The disk space under /opt/ must be greater than 61440 MB, currently it is 36907 MB

Could you extend the hard disk?

**Comment by willnx** [comment]
I'm sorry, but that's not how this works. I'm deploying the OVA that the DataIQ engineering team has released. If it was released with a flaw, the flaw stays. This is for posterity; user's can gain the same knowledge as a customer by encountering the same issue. Workarounds exist, so please use one of those, but I'm not going to automate a workaround/modify the default OVA that's released.
