### ISSUE TITLE
Error: Timed out on task 344da358-e56d-400e-bc21-443815db3d6a when trying to run 'vlab init'

### ISSUE THREAD

**Issue by vinumathew8881** [willnx/vlab#79]
Hello willnx,
I am trying to use the vlab simulator for OneFS, but I am unable to get past the deployment. 
FYI, I have SSH(putty), RDP, SCP(WinSCP) and VMRC clients as well as a supported browser(Chrome) installed on my machine. When I start the configuration using the 'vlab init' command, I run into the following error:

"Continue with config setup? [Yes/no] Yes
Great! Give me a couple of minutes to find those programs
Initializing your lab
Deploying gateway
Error: Timed out on task 344da358-e56d-400e-bc21-443815db3d6a"

Could you let me know what could be wrong here?

**Comment by vinumathew8881** [comment]
I found what the problem was. I ran 'vlab init' from an Administrator's powershell..I re-ran the init without it, and was able to deployment, but have run into another issue:

"This looks like a standard deployment, so pick some IPs between:
192.168.1.2 and 192.168.1.149
With the syntax of --external-ip-range in mind, what range of IPs do you want to use? 192.168.1.10 192.168.1.14
Deploying 1 node running 9.0.0.0
Initializing cluster isi01
Creating SSH and HTTPS mapping rules for each node
Error: unable to find host Vinu_K_M.vlab.emc.com for /api/1/ipam/portmap"

Any ideas how to correct this? I tried restarting the gateway. But it didn't help much.

**Comment by willnx** [comment]
@vinumathew8881 The admin shell is not the issue. Like, *your client* permissions have no impact on the vLab server. 

The vLab docs describe how the client (aka the CLI you installed) and the server interact asynchronously. When you issue something like `vlab create onefs...` the client receives a "ticket" from the server. You can think of this "ticket" like a task/job ID. While the little wheel spins on the CLI, it's just checking the status of that ticket/job id/ task id. The server works the "tickets," one after another. It's sort of like when you have to get your driver license updated in person. You walk into the DMV, grab a ticket, and wait for them to call you up to the counter.

When the client times out, it just gives up awaiting the server to fulfil the ticket. That's it. Running a shell with/without Admin powers wouldn't matter.

If you work at Dell EMC, you should checkout the docs and join our Slack channel. Much faster responses, and you wont be stuck awaiting just me; lots of other people have really good experience with vLab on our internal Slack channel! 😄

**Comment by vinumathew8881** [comment]
Alright! That makes a lot of sense, the fact that i re-ran the vlab init on the other shell and when it worked, made me believe that there was something related to my client permissions. 
Thanks for letting me know about the slack channel, I have just joined :) Will use that for further communications w.r.t vlab.
