### ISSUE TITLE
vLAB initialization 

### ISSUE THREAD

**Issue by madhusridas015** [willnx/vlab#82]
I need assistance as my vlab initialization won't work. 
I am following this guide to use it. https://vlab.emc.com/getting_started.html#initialize-your-lab 
Here if you see I have to run the command 'vlab init' command to initialize it, but it doesn't work. Please assist!
<img width="576" alt="vlab" src="https://user-images.githubusercontent.com/88035650/127146909-5e48672e-88b7-498a-b3d3-54d66a0192f0.png">

**Comment by willnx** [comment]
Howdy!

Not sure who told you to file an issue here for this, but it's not the right thing to do. Checkout the main page on the website at your work; there will be links to email and Slack for help. Please do not paste the link to the website here, or anything like that.

**Comment by madhusridas015** [comment]
My bad @willnx it's a genuine mistake. Someone from the helpdesk redirected me to do so. My apologies, I will take care of it 👍
