### ISSUE TITLE
Error: INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by CAVAZQUE** [willnx/vlab#83]
When I try to create a isilon node. the error appears:

PS C:\Users\xxxxx> vlab create onefs --name xxxxxx1 --image 8.2.1 --external-ip-range 192.168.1.20 192.168.1.23
Deploying 1 node running 8.2.1
Error: INTERNAL SERVER ERROR

PS C:\Users\xxxxxx> vlab status
Collecting information about your inventory
Error: INTERNAL SERVER ERROR
PS C:\Users\xxxxxx>

**Comment by willnx** [comment]
Hello,

You'll have to contact the vLab Admin for your environment. That error
points to an issue on the server.
I have no access to the server, so I cannot help.

Thanks,
-Nick
