### ISSUE TITLE
Allow growing virtual disk size for InsightIQ instances

### ISSUE THREAD

**Issue by danielchana** [willnx/vlab#84]
When importing InsightIQ data from other machine into vLab's IIQ instances, sometimes the imported data exceeds the default disk size of the instance (around 60 GiB by default).

There's a simple procedure to grow the IIQ partition if the virtual disk size is bigger, with IIQ always on (no reboot required), and it can even be scripted to make it simpler. However, the virtual disk size has to be bigger first.

So perhaps a great improvement would be a CLI option to define the data disk size before deploying the image, and then the user could do the partition growing inside the SO.

**Comment by willnx** [comment]
Hi @danielchana! I'm no longer actively developing for this system. You should reach out to your local admins with questions/feature requests. If you're from Dell, there's channels for Slack and MS Teams if you're not sure who the admins are. Pretty sure you can find the correct channel just by searching for `vlab`.
