### ISSUE TITLE
When trying to 'vlab connect centos' it show 'service unavailable'

### ISSUE THREAD

**Issue by sevenstreak** [willnx/vlab#85]
![image](https://user-images.githubusercontent.com/6712069/141426637-0efcf176-33d0-4bf0-a07c-a4696e2ad2a2.png)

vlab continually shows that it's initializing but even after restarting the nodes still it shows "service unavailable" when trying to connect.

Even refreshed my  token with the same results.

**Comment by willnx** [comment]
I'm sorry, but I no longer manage vLab. Please contact your local admin.
