### ISSUE TITLE
Can't create router

### ISSUE THREAD

**Issue by LeonardoMor** [willnx/vlab#88]
`PS C:\Users\leonardo_mora> vlab --version
vlab, version 2021.7.16`
**Command I ran and output:**
`PS C:\Users\leonardo_mora> vlab create router --name testrouter --networks frontend --networks testnet --image 1.1.8
Creating a new router for networks frontend testnet
Error: INTERNAL SERVER ERROR`
I expected a router to be created.

**Comment by willnx** [comment]
You'll have to contact your local VM admin. I no longer have access to the system, and as such, cannot debug the issue. sorry.
